version: '3.8'

services:
  logistic-api:
    image: docker.io/sipky/logistic-api
    container_name: logistic-api
    ports:
      - "8080:8080"
    depends_on:
      - db
      
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: logistic
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
